CONNECT "C:\Users\Artem\Desktop\DB\STUDENTS.FDB";

CREATE TABLE groups(
    id INTEGER,
    name VARCHAR(10)
);

INSERT INTO groups VALUES(1, 'B8102');
INSERT INTO groups VALUES(2, 'B8103');
INSERT INTO groups VALUES(3, 'B8203a');
INSERT INTO groups VALUES(4, 'C8434');
INSERT INTO groups VALUES(5, 'E5604');
